version: "3.9"
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    working_dir: /code
  scheduler:
    build: .
    command: python scripts/run_scheduler.py
    env_file:
      - .env
    volumes:
      - .:/code
    working_dir: /code
