prompt_path: "app/prompts/readiness_prompt.txt"
historical_context_path: "app/prompts/historical_context.txt"

default_language: en

translations:
  en:
    instruction: >
      Respond entirely in English. Write concise, actionable explanations while keeping all JSON keys exactly as specified.
  de:
    instruction: >
      Antworte ausschließlich in deutscher Sprache. Formuliere alle erklärenden Texte, Aufzählungen, Tipps und Begründungen auf Deutsch, lasse die JSON-Schlüssel jedoch unverändert in Englisch.

thresholds:
  readiness:
    critical: 20
    poor: 40
    low: 60
    moderate: 75
  hrv_drop_pct: 10
  resting_hr_elevated_bpm: 5
  sleep_hours_min: 6
  acwr_moderate: 1.3
  acwr_high: 1.5
  no_rest_days: 7

activity_classification:
  training_effect:
    high_impact_threshold: 3.0
    moderate_impact_threshold: 2.5
    very_high_threshold: 4.0
  heart_rate:
    zone_threshold: 0.7
    high_intensity_threshold: 0.85
  duration:
    minimum_seconds: 1800
    long_duration_minutes: 90
