prompt_path: "app/prompts/readiness_prompt.txt"
historical_context_path: "app/prompts/historical_context.txt"

thresholds:
  readiness:
    critical: 20
    poor: 40
    low: 60
    moderate: 75
  hrv_drop_pct: 10
  resting_hr_elevated_bpm: 5
  sleep_hours_min: 6
  acwr_moderate: 1.3
  acwr_high: 1.5
  no_rest_days: 7
