prompt_path: "app/prompts/readiness_prompt.txt"
historical_context_path: "app/prompts/historical_context.txt"

default_language: en

translations:
  en:
    instruction: >
      Respond entirely in English. Write concise, actionable explanations while keeping all JSON keys exactly as specified.
  de:
    instruction: >
      Antworte ausschließlich in deutscher Sprache. Formuliere alle erklärenden Texte, Aufzählungen, Tipps und Begründungen auf Deutsch, lasse die JSON-Schlüssel jedoch unverändert in Englisch.

thresholds:
  readiness:
    critical: 20
    poor: 40
    moderate_low: 60  # Renamed from "low" for clarity (was confusing with Garmin's "low" label)
    moderate: 75
    good: 90  # Added for completeness
  hrv_drop_pct: 10
  resting_hr_elevated_bpm: 5
  sleep_hours_min: 6
  acwr_moderate: 1.3
  acwr_high: 1.5
  no_rest_days: 7

activity_classification:
  training_effect:
    high_impact_threshold: 3.0
    moderate_impact_threshold: 2.5
    very_high_threshold: 4.0
  heart_rate:
    zone_threshold: 0.7
    high_intensity_threshold: 0.85
  duration:
    minimum_seconds: 1800
    long_duration_minutes: 90

performance_analysis:
  workout_recency_hours: 72  # Hours to consider workout "recent" for analysis
  min_duration_seconds: 300  # Minimum 5 minutes to count as workout
  similar_workout_lookback_days: 14  # Days to look back for similar workout comparisons
  min_similar_workouts: 2  # Minimum workouts needed to calculate trend
  hr_deviation_threshold: 5  # bpm deviation to flag as significant
  pace_deviation_threshold_pct: 5  # Percent deviation to flag as significant
  stable_threshold: 5.0  # Threshold for "stable" trend (within ±5%)

alert_detection:
  overtraining:
    hrv_drop:
      warning: 15  # % drop from baseline
      critical: 25  # % drop from baseline
    consecutive_hard_days:
      warning: 3  # consecutive high-intensity days
      critical: 5  # consecutive high-intensity days
    sleep_debt:
      warning: 3  # hours of sleep debt
      critical: 6  # hours of sleep debt
    messages:
      warning:
        title: "Overtraining Warning"
        message: "You're showing early signs of overtraining: {hrv_info}{consecutive_days_info}{sleep_info}"
        recommendation: "Consider taking an easy day or rest day. Monitor your recovery metrics closely."
      critical:
        title: "Critical Overtraining Risk"
        message: "Multiple overtraining indicators detected: {hrv_info}{consecutive_days_info}{sleep_info}"
        recommendation: "Take immediate rest. Do not train until recovery metrics improve."

  illness:
    warning:
      hrv_drop_percent: 20  # % drop
      rhr_increase_bpm: 5  # bpm increase
      consecutive_days: 2  # days with both signals
    critical:
      hrv_drop_percent: 30  # % drop
      rhr_increase_bpm: 10  # bpm increase
      consecutive_days: 1  # days with both signals
    messages:
      warning:
        title: "Possible Illness Risk"
        message: "Your HRV has dropped {hrv_drop}% and resting heart rate is elevated by {rhr_increase} bpm for {days} days."
        recommendation: "Monitor symptoms. Consider light activity only. Prioritize sleep and hydration."
      critical:
        title: "Strong Illness Indicators"
        message: "Significant physiological stress detected: HRV down {hrv_drop}%, RHR up {rhr_increase} bpm."
        recommendation: "Rest completely. Consult a healthcare provider if symptoms persist."

  injury:
    acwr:
      warning: 1.3  # acute:chronic workload ratio
      critical: 1.5  # acute:chronic workload ratio
      comeback_threshold: 0.8  # below this = comeback injury pattern
    weekly_load_increase:
      warning: 15  # % increase week-over-week
      critical: 25  # % increase week-over-week
    messages:
      # Context-aware messages based on ACWR pattern
      comeback_warning:
        title: "Comeback Injury Risk"
        message: "Rapid load increase after rest period: {load_info}. ACWR {acwr:.2f} indicates you're doing too much too soon."
        recommendation: "Gradual progression needed. Limit weekly load increases to 10% until ACWR reaches 0.8-1.0."
      comeback_critical:
        title: "High Comeback Injury Risk"
        message: "Dangerous comeback spike: {load_info}. ACWR {acwr:.2f} shows you're ramping up too aggressively after downtime."
        recommendation: "IMMEDIATE volume reduction. Take 2-3 easy days, then resume at 50% current volume. Build gradually."
      overtraining_warning:
        title: "Overtraining Injury Risk"
        message: "Chronic overload detected: {load_info}. ACWR {acwr:.2f} indicates sustained high training stress."
        recommendation: "Reduce training volume by 20-30%. Take a rest day, then focus on recovery runs for the week."
      overtraining_critical:
        title: "High Overtraining Injury Risk"
        message: "Severe overtraining pattern: {load_info}. ACWR {acwr:.2f} shows dangerous cumulative fatigue."
        recommendation: "MANDATORY rest. Take 3-4 easy days minimum. Consider full rest week if symptoms persist."
      # Generic fallback (when ACWR not available)
      warning:
        title: "Injury Risk Warning"
        message: "Training load increasing too quickly: {load_info}"
        recommendation: "Reduce training volume by 10-20% this week. Focus on recovery quality."
      critical:
        title: "High Injury Risk"
        message: "Dangerous training load spike detected: {load_info}"
        recommendation: "Immediate volume reduction required. Take 2-3 easy days before resuming normal training."
